import{loadSession,saveSession,signIn,createFirstAccess,resendConfirmation,adminApi,procurementApi,emergencyApi,productImageApi,uploadProductImage,money,cents,esc,option,table}from"./admin-api.js?v=20261001-shippingadmin1";
import{shell,renderDashboard}from"./admin-view.js?v=20261001-shippingadmin1";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const login=$("#loginView"),app=$("#app"),content=$("#adminContent"),msg=$("#loginMessage"),toast=$("#toast");
let data=null;
function notify(t){toast.textContent=t;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2800)}
function bindTabs(){$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("is-active",x===b));$$(".tab-panel").forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab);if(b.dataset.tab==="compras")loadSuppliers();if(b.dataset.tab==="relatorios")runReports();if(b.dataset.tab==="emergencia")loadStatus()})}
async function refresh(){data=(await adminApi({action:"dashboard"})).data;renderDashboard(data)}
async function open(){const fresh=(await adminApi({action:"dashboard"})).data;data=fresh;content.innerHTML=shell();login.hidden=true;app.hidden=false;bindTabs();bindForms();renderDashboard(data)}
async function loadSuppliers(){try{const a=(await procurementApi({action:"list_suppliers"})).data||[];$("#lotSupplier").innerHTML=option(a,"id","name","Sem fornecedor")}catch(e){notify(e.message)}}
function setPreview(input,preview){const file=input?.files?.[0];if(!preview)return;if(!file){preview.hidden=true;preview.removeAttribute("src");return}preview.src=URL.createObjectURL(file);preview.hidden=false}
function productPayload(f,includeActive=false){const p={name:f.get("name"),brand:f.get("brand"),product_type:f.get("product_type")||"perfume",category:f.get("category"),volume_ml:Number(f.get("volume_ml")),price_cents:cents(f.get("price")),sale_price_cents:f.get("sale_price")?cents(f.get("sale_price")):null,weight_kg:Number(f.get("weight_kg")||.5),width_cm:Number(f.get("width_cm")||12),height_cm:Number(f.get("height_cm")||15),length_cm:Number(f.get("length_cm")||8),short_description:f.get("short_description"),description:f.get("description"),composition:f.get("composition"),top_notes:f.get("top_notes"),heart_notes:f.get("heart_notes"),base_notes:f.get("base_notes"),is_featured:f.get("is_featured")==="on",is_best_seller:f.get("is_best_seller")==="on"};if(includeActive)p.is_active=f.get("is_active")==="on";return p}
function openProductEditor(id){const p=data?.products?.find(x=>x.id===id);if(!p)return notify("Perfume não encontrado.");const card=$("#editProductCard"),form=$("#editProductForm");form.elements.id.value=p.id;form.elements.name.value=p.name||"";form.elements.brand.value=p.brand||"";form.elements.product_type.value=p.product_type||"perfume";form.elements.category.value=p.category||"masculino";form.elements.volume_ml.value=p.volume_ml||"";form.elements.price.value=(Number(p.price_cents||0)/100).toFixed(2);form.elements.sale_price.value=p.sale_price_cents!=null?(Number(p.sale_price_cents)/100).toFixed(2):"";form.elements.weight_kg.value=Number(p.weight_kg||.5);form.elements.width_cm.value=Number(p.width_cm||12);form.elements.height_cm.value=Number(p.height_cm||15);form.elements.length_cm.value=Number(p.length_cm||8);form.elements.short_description.value=p.short_description||"";form.elements.description.value=p.description||"";form.elements.composition.value=p.composition||"";form.elements.top_notes.value=(p.top_notes||[]).join(", ");form.elements.heart_notes.value=(p.heart_notes||[]).join(", ");form.elements.base_notes.value=(p.base_notes||[]).join(", ");form.elements.is_featured.checked=!!p.is_featured;form.elements.is_best_seller.checked=!!p.is_best_seller;form.elements.is_active.checked=!!p.is_active;form.elements.image.value="";const preview=$("#editProductImagePreview");if(p.image_url){preview.src=p.image_url;preview.hidden=false}else{preview.hidden=true;preview.removeAttribute("src")}card.hidden=false;card.scrollIntoView({behavior:"smooth",block:"start"})}
function closeProductEditor(){const card=$("#editProductCard"),form=$("#editProductForm");if(form)form.reset();if(card)card.hidden=true}
function openSellerEditor(id){const s=data?.sellers?.find(x=>x.id===id);if(!s)return notify("Vendedor não encontrado.");const card=$("#editSellerCard"),form=$("#editSellerForm");form.elements.id.value=s.id;form.elements.name.value=s.name||"";form.elements.email.value=s.email||"";form.elements.whatsapp_number.value=s.whatsapp_number||"";form.elements.avatar_url.value=s.avatar_url||"";form.elements.bio.value=s.bio||"";form.elements.city_id.value=(s.city_ids||[])[0]||"";form.elements.can_toggle.checked=!!s.can_toggle_site_emergency;form.elements.is_active.checked=!!s.is_active;card.hidden=false;card.scrollIntoView({behavior:"smooth",block:"start"})}
function closeSellerEditor(){const card=$("#editSellerCard"),form=$("#editSellerForm");if(form)form.reset();if(card)card.hidden=true}
function bindForms(){
$("#productImage").onchange=e=>setPreview(e.target,$("#productImagePreview"));
$("#editProductImage").onchange=e=>setPreview(e.target,$("#editProductImagePreview"));

$("#productForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form),file=f.get("image");try{notify("Enviando foto...");const imageUrl=await uploadProductImage(file);const created=await adminApi({action:"create_product",...productPayload(f)});await productImageApi({product_id:created.data.id,image_url:imageUrl});form.reset();const preview=$("#productImagePreview");preview.hidden=true;preview.removeAttribute("src");await refresh();notify("Produto cadastrado com foto e notas.")}catch(x){notify(x.message)}};

$("#editProductForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get("id"),file=f.get("image");try{notify("Salvando alterações...");await adminApi({action:"update_product",id,...productPayload(f,true)});if(file instanceof File&&file.size){const imageUrl=await uploadProductImage(file);await productImageApi({product_id:id,image_url:imageUrl})}await refresh();closeProductEditor();notify("Perfume atualizado.")}catch(x){notify(x.message)}};
$("#cancelEditProduct").onclick=closeProductEditor;

content.addEventListener("click",async e=>{const saveOrder=e.target.closest("[data-save-order]"),editSeller=e.target.closest("[data-edit-seller]"),edit=e.target.closest("[data-edit-product]"),del=e.target.closest("[data-delete-product]"),restore=e.target.closest("[data-restore-product]");if(saveOrder){const id=saveOrder.dataset.saveOrder,fulfillment=document.querySelector('[data-order-fulfillment="'+id+'"]')?.value,payment=document.querySelector('[data-order-payment="'+id+'"]')?.value;try{await adminApi({action:"update_order_status",id,fulfillment_status:fulfillment,payment_status:payment});await refresh();notify("Pedido atualizado.")}catch(x){notify(x.message)}return}if(editSeller){openSellerEditor(editSeller.dataset.editSeller);return}if(edit){openProductEditor(edit.dataset.editProduct);return}if(del){const p=data?.products?.find(x=>x.id===del.dataset.deleteProduct);if(!confirm('Excluir "'+(p?.name||"este perfume")+'" da loja? O histórico será preservado.'))return;try{await adminApi({action:"delete_product",id:del.dataset.deleteProduct});await refresh();closeProductEditor();notify("Perfume removido da loja.")}catch(x){notify(x.message)}return}if(restore){try{await adminApi({action:"restore_product",id:restore.dataset.restoreProduct});await refresh();notify("Perfume restaurado na loja.")}catch(x){notify(x.message)}}});

$("#cityForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{const r=await adminApi({action:"create_city",city_name:f.get("city_name"),state_name:f.get("state_name"),country_code:f.get("country_code")});form.reset();await refresh();notify(r?.already_exists?"Cidade já estava cadastrada e continua ativa.":r?.restored?"Cidade reativada.":"Cidade cadastrada.");$("#cities")?.scrollIntoView({behavior:"smooth",block:"nearest"})}catch(x){notify(x.message==="CITY_CREATE_FAILED"?"Não foi possível cadastrar a cidade. Verifique os dados e tente novamente.":x.message)}};
$("#sellerForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{await adminApi({action:"create_seller",name:f.get("name"),email:f.get("email"),whatsapp_number:f.get("whatsapp_number"),avatar_url:f.get("avatar_url"),bio:f.get("bio"),city_ids:f.get("city_id")?[f.get("city_id")]:[],can_toggle_site_emergency:f.get("can_toggle")==="on"});form.reset();await refresh();notify("Vendedor cadastrado.")}catch(x){notify(x.message)}};

$("#editSellerForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{notify("Salvando vendedor...");await adminApi({action:"update_seller",id:f.get("id"),name:f.get("name"),email:f.get("email"),whatsapp_number:f.get("whatsapp_number"),avatar_url:f.get("avatar_url"),bio:f.get("bio"),city_ids:f.get("city_id")?[f.get("city_id")]:[],can_toggle_site_emergency:f.get("can_toggle")==="on",is_active:f.get("is_active")==="on"});await refresh();closeSellerEditor();notify("Cadastro do vendedor atualizado.")}catch(x){notify(x.message==="SELLER_AUTH_EMAIL_UPDATE_FAILED"?"Os demais dados foram salvos, mas não foi possível atualizar o e-mail de login.":x.message)}};
$("#cancelEditSeller").onclick=closeSellerEditor;
$("#locationForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{await adminApi({action:"create_location",name:f.get("name"),service_city_id:f.get("city_id"),seller_id:f.get("seller_id")});form.reset();await refresh();notify("Estoque criado.")}catch(x){notify(x.message)}};
$("#adjustForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{await adminApi({action:"adjust_inventory",location_id:f.get("location_id"),product_id:f.get("product_id"),quantity_delta:Number(f.get("qty")),reason_code:f.get("reason"),financial_impact_cents:cents(f.get("impact")),note:f.get("note")});form.reset();await refresh();notify("Movimentação registrada.")}catch(x){notify(x.message)}};
$("#supplierForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{await procurementApi({action:"create_supplier",supplier:{name:f.get("name"),contact_name:f.get("contact"),phone:f.get("phone"),notes:f.get("notes")}});form.reset();await loadSuppliers();notify("Fornecedor salvo.")}catch(x){notify(x.message)}};
$("#lotForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form),loc=data.locations.find(x=>x.id===f.get("location_id"));try{await procurementApi({action:"create_purchase_lot",lot:{supplier_id:f.get("supplier_id")||null,service_city_id:loc?.service_city_id||null},items:[{product_id:f.get("product_id"),quantity:Number(f.get("qty")),unit_cost_cents:cents(f.get("cost")),risk_type:f.get("risk")||null,risk_value_cents:cents(f.get("risk_value")),risk_note:f.get("risk_note")||null}]});await adminApi({action:"adjust_inventory",location_id:f.get("location_id"),product_id:f.get("product_id"),quantity_delta:Number(f.get("qty")),reason_code:"restock",financial_impact_cents:0,note:"Entrada por lote"});form.reset();await refresh();notify("Lote registrado e estoque atualizado.")}catch(x){notify(x.message)}};
$("#shippingSettingsForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{const cep=String(f.get("origin_postal_code")||"").replace(/\D/g,"");if(cep&&cep.length!==8)return notify("Informe um CEP de origem válido.");await adminApi({action:"update_shipping_settings",origin_postal_code:cep,provider_environment:f.get("provider_environment"),shipping_enabled:f.get("shipping_enabled")==="on",public_note:f.get("public_note")});await refresh();notify("Configuração de frete salva.")}catch(x){notify(x.message)}};
$("#runReport").onclick=runReports;
$("#disableSite").onclick=async()=>{const reason=$("#outageReason").value.trim();if(reason.length<3)return notify("Informe a justificativa.");if(!confirm("Confirma retirar a loja do ar?"))return;try{await emergencyApi({action:"set_status",is_online:false,outage_kind:$("#outageKind").value,outage_reason:reason,public_message:$("#publicMessage").value.trim()});await loadStatus();notify("Loja desativada.")}catch(e){notify(e.message)}};
$("#enableSite").onclick=async()=>{if(!confirm("Confirma reativar a loja?"))return;try{await emergencyApi({action:"set_status",is_online:true,outage_reason:$("#restoreReason").value.trim()});await loadStatus();notify("Loja reativada.")}catch(e){notify(e.message)}};
}
async function loadStatus(){try{const s=(await emergencyApi({action:"get_status"})).data;$("#statusDot").className="status-dot "+(s.is_online?"online":"offline");$("#statusText").textContent=s.is_online?"Loja online":"Loja fora do ar";$("#statusDetail").textContent=s.is_online?"A vitrine está disponível.":(s.outage_kind||"Indisponível")+" · "+(s.outage_reason||"")}catch(e){notify(e.message)}}
async function runReports(){if(!$("#reportMetrics"))return;try{const r=(await adminApi({action:"reports",from:$("#from").value,to:$("#to").value,seller_id:$("#reportSeller").value,product_id:$("#reportProduct").value,city_id:$("#reportCity").value})).data,s=r.summary;$("#reportMetrics").innerHTML=[["Vendas",money(s.sales_cents)],["Lucro bruto",money(s.gross_profit_cents)],["Margem",s.gross_margin_percent+"%"],["Perdas",money(s.loss_cents)],["Brindes",money(s.gift_cents)],["Perda estrada",money(s.road_loss_cents)],["Resultado",money(s.net_operational_cents)]].map(x=>'<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join("");$("#reportMoves").innerHTML=table([["Data",x=>new Date(x.created_at).toLocaleString("pt-BR")],["Produto",x=>esc(x.product_name)],["Cidade",x=>esc(x.city_name||"—")],["Motivo",x=>esc(x.reason_code||"—")],["Qtd.",x=>x.quantity_delta],["Impacto",x=>money(x.financial_impact_cents)],["Nota",x=>esc(x.note||"—")]],r.movements||[]);$("#reportRisks").innerHTML=table([["Produto",x=>esc(x.product_name)],["Risco",x=>esc(x.risk_type||"—")],["Valor",x=>money(x.risk_value_cents)],["Qtd.",x=>x.quantity]],r.risks||[])}catch(e){notify(e.message)}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();msg.textContent="";try{await signIn($("#email").value.trim(),$("#password").value);await open()}catch(x){saveSession(null);msg.textContent=x.message}};
$("#createAccess").onclick=async()=>{msg.textContent="";try{const d=await createFirstAccess($("#email").value.trim(),$("#password").value);if(d.access_token)await open();else msg.textContent="Conta criada. Confirme o e-mail recebido e depois entre. Se não encontrar a mensagem, use “Reenviar confirmação”."}catch(x){msg.textContent=x.message}};
$("#resendConfirm").onclick=async()=>{msg.textContent="";try{await resendConfirmation($("#email").value.trim());msg.textContent="E-mail de confirmação reenviado. Abra sua caixa de entrada, confirme o acesso e depois entre normalmente."}catch(x){msg.textContent=x.message}};
$("#logout").onclick=()=>{saveSession(null);location.reload()};
(async()=>{if(!loadSession()?.access_token)return;try{await open()}catch(e){if(e?.status===401){saveSession(null);login.hidden=false;app.hidden=true;msg.textContent="Sua sessão expirou. Entre novamente."}else{login.hidden=false;app.hidden=true;msg.textContent=e?.message||"Não foi possível carregar o painel. Tente novamente."}}})();