import{loadSession,saveSession,signIn,createFirstAccess,resendConfirmation,adminApi,procurementApi,emergencyApi,productImageApi,uploadProductImage,money,cents,esc,option,table}from"./admin-api.js?v=20260930-2220";
import{shell,renderDashboard}from"./admin-view.js?v=20260930-2220";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const login=$("#loginView"),app=$("#app"),content=$("#adminContent"),msg=$("#loginMessage"),toast=$("#toast");
let data=null;
function notify(t){toast.textContent=t;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2600)}
function bindTabs(){$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("is-active",x===b));$$(".tab-panel").forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab);if(b.dataset.tab==="compras")loadSuppliers();if(b.dataset.tab==="relatorios")runReports();if(b.dataset.tab==="emergencia")loadStatus()})}
async function refresh(){data=(await adminApi({action:"dashboard"})).data;renderDashboard(data)}
async function open(){const fresh=(await adminApi({action:"dashboard"})).data;data=fresh;content.innerHTML=shell();login.hidden=true;app.hidden=false;bindTabs();bindForms();renderDashboard(data)}
async function loadSuppliers(){try{const a=(await procurementApi({action:"list_suppliers"})).data||[];$("#lotSupplier").innerHTML=option(a,"id","name","Sem fornecedor")}catch(e){notify(e.message)}}
function bindForms(){
$("#productImage").onchange=e=>{const file=e.target.files?.[0],preview=$("#productImagePreview");if(!file){preview.hidden=true;preview.removeAttribute("src");return}preview.src=URL.createObjectURL(file);preview.hidden=false};
$("#productForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get("image");try{notify("Enviando foto...");const imageUrl=await uploadProductImage(file);const created=await adminApi({action:"create_product",name:f.get("name"),brand:f.get("brand"),category:f.get("category"),volume_ml:Number(f.get("volume_ml")),price_cents:cents(f.get("price")),sale_price_cents:f.get("sale_price")?cents(f.get("sale_price")):null,description:f.get("description"),composition:f.get("composition")});await productImageApi({product_id:created.data.id,image_url:imageUrl});e.currentTarget.reset();const preview=$("#productImagePreview");preview.hidden=true;preview.removeAttribute("src");await refresh();notify("Perfume e foto cadastrados.")}catch(x){notify(x.message)}};
$("#cityForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await adminApi({action:"create_city",city_name:f.get("city_name"),state_name:f.get("state_name"),country_code:f.get("country_code")});e.currentTarget.reset();await refresh();notify("Cidade cadastrada.")}catch(x){notify(x.message)}};
$("#sellerForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await adminApi({action:"create_seller",name:f.get("name"),email:f.get("email"),whatsapp_number:f.get("whatsapp_number"),avatar_url:f.get("avatar_url"),city_ids:f.get("city_id")?[f.get("city_id")]:[],can_toggle_site_emergency:f.get("can_toggle")==="on"});e.currentTarget.reset();await refresh();notify("Vendedor cadastrado.")}catch(x){notify(x.message)}};
$("#locationForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await adminApi({action:"create_location",name:f.get("name"),service_city_id:f.get("city_id"),seller_id:f.get("seller_id")});e.currentTarget.reset();await refresh();notify("Estoque criado.")}catch(x){notify(x.message)}};
$("#adjustForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await adminApi({action:"adjust_inventory",location_id:f.get("location_id"),product_id:f.get("product_id"),quantity_delta:Number(f.get("qty")),reason_code:f.get("reason"),financial_impact_cents:cents(f.get("impact")),note:f.get("note")});e.currentTarget.reset();await refresh();notify("Movimentação registrada.")}catch(x){notify(x.message)}};
$("#supplierForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await procurementApi({action:"create_supplier",supplier:{name:f.get("name"),contact_name:f.get("contact"),phone:f.get("phone"),notes:f.get("notes")}});e.currentTarget.reset();await loadSuppliers();notify("Fornecedor salvo.")}catch(x){notify(x.message)}};
$("#lotForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),loc=data.locations.find(x=>x.id===f.get("location_id"));try{await procurementApi({action:"create_purchase_lot",lot:{supplier_id:f.get("supplier_id")||null,service_city_id:loc?.service_city_id||null},items:[{product_id:f.get("product_id"),quantity:Number(f.get("qty")),unit_cost_cents:cents(f.get("cost")),risk_type:f.get("risk")||null,risk_value_cents:cents(f.get("risk_value")),risk_note:f.get("risk_note")||null}]});await adminApi({action:"adjust_inventory",location_id:f.get("location_id"),product_id:f.get("product_id"),quantity_delta:Number(f.get("qty")),reason_code:"restock",financial_impact_cents:0,note:"Entrada por lote"});e.currentTarget.reset();await refresh();notify("Lote registrado e estoque atualizado.")}catch(x){notify(x.message)}};
$("#runReport").onclick=runReports;
$("#disableSite").onclick=async()=>{const reason=$("#outageReason").value.trim();if(reason.length<3)return notify("Informe a justificativa.");if(!confirm("Confirma retirar a loja do ar?"))return;try{await emergencyApi({action:"set_status",is_online:false,outage_kind:$("#outageKind").value,outage_reason:reason,public_message:$("#publicMessage").value.trim()});await loadStatus();notify("Loja desativada.")}catch(e){notify(e.message)}};
$("#enableSite").onclick=async()=>{if(!confirm("Confirma reativar a loja?"))return;try{await emergencyApi({action:"set_status",is_online:true,outage_reason:$("#restoreReason").value.trim()});await loadStatus();notify("Loja reativada.")}catch(e){notify(e.message)}};
}
async function loadStatus(){try{const s=(await emergencyApi({action:"get_status"})).data;$("#statusDot").className="status-dot "+(s.is_online?"online":"offline");$("#statusText").textContent=s.is_online?"Loja online":"Loja fora do ar";$("#statusDetail").textContent=s.is_online?"A vitrine está disponível.":(s.outage_kind||"Indisponível")+" · "+(s.outage_reason||"")}catch(e){notify(e.message)}}
async function runReports(){if(!$("#reportMetrics"))return;try{const r=(await adminApi({action:"reports",from:$("#from").value,to:$("#to").value,seller_id:$("#reportSeller").value,product_id:$("#reportProduct").value,city_id:$("#reportCity").value})).data,s=r.summary;$("#reportMetrics").innerHTML=[["Vendas",money(s.sales_cents)],["Lucro bruto",money(s.gross_profit_cents)],["Margem",s.gross_margin_percent+"%"],["Perdas",money(s.loss_cents)],["Brindes",money(s.gift_cents)],["Perda estrada",money(s.road_loss_cents)],["Resultado",money(s.net_operational_cents)]].map(x=>'<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join("");$("#reportMoves").innerHTML=table([["Data",x=>new Date(x.created_at).toLocaleString("pt-BR")],["Produto",x=>esc(x.product_name)],["Cidade",x=>esc(x.city_name||"—")],["Motivo",x=>esc(x.reason_code||"—")],["Qtd.",x=>x.quantity_delta],["Impacto",x=>money(x.financial_impact_cents)],["Nota",x=>esc(x.note||"—")]],r.movements||[]);$("#reportRisks").innerHTML=table([["Produto",x=>esc(x.product_name)],["Risco",x=>esc(x.risk_type||"—")],["Valor",x=>money(x.risk_value_cents)],["Qtd.",x=>x.quantity]],r.risks||[])}catch(e){notify(e.message)}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();msg.textContent="";try{await signIn($("#email").value.trim(),$("#password").value);await open()}catch(x){saveSession(null);msg.textContent=x.message}};
$("#createAccess").onclick=async()=>{msg.textContent="";try{const d=await createFirstAccess($("#email").value.trim(),$("#password").value);if(d.access_token)await open();else msg.textContent="Conta criada. Confirme o e-mail recebido e depois entre. Se não encontrar a mensagem, use “Reenviar confirmação”."}catch(x){msg.textContent=x.message}};
$("#resendConfirm").onclick=async()=>{msg.textContent="";try{await resendConfirmation($("#email").value.trim());msg.textContent="E-mail de confirmação reenviado. Abra sua caixa de entrada, confirme o acesso e depois entre normalmente."}catch(x){msg.textContent=x.message}};
$("#logout").onclick=()=>{saveSession(null);location.reload()};
(async()=>{if(!loadSession()?.access_token)return;try{await open()}catch(e){if(e?.status===401){saveSession(null);login.hidden=false;app.hidden=true;msg.textContent="Sua sessão expirou. Entre novamente."}else{login.hidden=false;app.hidden=true;msg.textContent=e?.message||"Não foi possível carregar o painel. Tente novamente."}}})();