const SUPABASE_URL="https://fbwlprwhczxjdsciotsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_XkqHZE_hdTNrNXE0O9tvRA_rWdw5pPE";
const SPRITE_INDEX={"velora-noir":0,"solaris-elixir":1,"fleur-dambre":2,"nero-absolu":3,"eclat-rose":4,"vertige":5};
const state={products:[],reviews:[],sellers:[],selectedSellerId:null,filter:"todos",search:"",bag:loadBag(),selectedProduct:null,payment:"pix"};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const els={productGrid:$("#productGrid"),catalogStatus:$("#catalogStatus"),catalogSearch:$("#catalogSearch"),productOverlay:$("#productOverlay"),productModalContent:$("#productModalContent"),bagBtn:$("#bagBtn"),bagCount:$("#bagCount"),bagDrawer:$("#bagDrawer"),closeBag:$("#closeBag"),drawerMask:$("#drawerMask"),bagItems:$("#bagItems"),bagTotal:$("#bagTotal"),checkoutBtn:$("#checkoutBtn"),checkoutOverlay:$("#checkoutOverlay"),checkoutSummary:$("#checkoutSummary"),checkoutForm:$("#checkoutForm"),paymentDemoBox:$("#paymentDemoBox"),sellerPicker:$("#sellerPicker"),toast:$("#toast"),siteUnavailable:$("#siteUnavailable"),siteUnavailableTitle:$("#siteUnavailableTitle"),siteUnavailableMessage:$("#siteUnavailableMessage")};
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function brl(c){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(c||0)/100)}
function spriteClass(p){return "sprite-"+(SPRITE_INDEX[p?.slug]??3)}
function visual(p,extra=""){return p?.image_url?'<img class="'+extra+'" src="'+esc(p.image_url)+'" alt="Foto de '+esc(p.name)+'" loading="lazy">':'<div class="sprite-art '+spriteClass(p)+' '+extra+'" role="img" aria-label="Foto de '+esc(p?.name||"perfume")+'"></div>'}
function loadBag(){try{return JSON.parse(localStorage.getItem("perfumes-demo-bag")||"[]")}catch{return[]}}
function saveBag(){localStorage.setItem("perfumes-demo-bag",JSON.stringify(state.bag))}
function toast(m){els.toast.textContent=m;els.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove("show"),2400)}
async function supabaseGet(table,query=""){const r=await fetch(SUPABASE_URL+"/rest/v1/"+table+"?"+query,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Accept:"application/json"}});if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadSiteStatus(){try{const rows=await supabaseGet("site_status","select=is_online,outage_kind,public_message,changed_at&id=eq.true&limit=1"),s=rows[0];if(!s||s.is_online){els.siteUnavailable.hidden=true;return}const permanent=s.outage_kind==="permanent_closure";els.siteUnavailableTitle.textContent=permanent?"Loja encerrada":"Site temporariamente indisponível";els.siteUnavailableMessage.textContent=s.public_message||(s.outage_kind==="inventory_count"?"Estamos realizando uma conferência de estoque. Voltamos em breve.":"Estamos realizando um ajuste operacional. Voltamos em breve.");els.siteUnavailable.hidden=false}catch(e){console.error(e)}}
async function loadSellers(){try{state.sellers=await supabaseGet("seller_checkout_options","select=seller_id,display_name,avatar_url&is_active=eq.true&order=display_name.asc");renderSellerPicker()}catch(e){console.error(e);els.sellerPicker.innerHTML='<p class="seller-picker-empty">Nenhum vendedor disponível agora.</p>'}}
function renderSellerPicker(){if(!state.sellers.length){els.sellerPicker.innerHTML='<p class="seller-picker-empty">Nenhum vendedor ativo cadastrado no momento.</p>';return}els.sellerPicker.innerHTML=state.sellers.map(s=>{const initial=esc((s.display_name||"?").trim().charAt(0).toUpperCase()),avatar=s.avatar_url?'<img src="'+esc(s.avatar_url)+'" alt="">':initial;return '<button class="seller-card '+(state.selectedSellerId===s.seller_id?"is-active":"")+'" type="button" data-seller-id="'+esc(s.seller_id)+'"><span class="seller-avatar">'+avatar+'</span><span class="seller-card-copy"><strong>'+esc(s.display_name)+'</strong><span>Selecionar vendedor</span></span></button>'}).join("");$$("[data-seller-id]",els.sellerPicker).forEach(b=>b.addEventListener("click",()=>{state.selectedSellerId=b.dataset.sellerId;renderSellerPicker()}))}
async function loadCatalog(){els.catalogStatus.textContent="Carregando catálogo...";try{const [products,reviews]=await Promise.all([supabaseGet("products","select=*&is_active=eq.true&order=is_featured.desc,created_at.asc"),supabaseGet("reviews","select=id,product_id,customer_name,rating,comment,is_verified_purchase,is_approved,created_at&is_approved=eq.true&order=created_at.asc")]);state.products=products;state.reviews=reviews;renderProducts();renderBag()}catch(e){console.error(e);els.catalogStatus.textContent="Não foi possível carregar o catálogo agora.";els.productGrid.innerHTML='<div class="empty-bag">O catálogo ficou temporariamente indisponível. Atualize a página em alguns instantes.</div>'}}
function filteredProducts(){let rows=state.filter==="todos"?state.products:state.products.filter(p=>p.category===state.filter);const q=state.search.trim().toLowerCase();if(q)rows=rows.filter(p=>[p.name,p.brand,p.category,String(p.volume_ml)].filter(Boolean).join(" ").toLowerCase().includes(q));return rows}
function renderProducts(){const products=filteredProducts();els.catalogStatus.textContent=products.length?products.length+" fragrância"+(products.length===1?"":"s")+" encontrada"+(products.length===1?"":"s"):"Nenhuma fragrância encontrada.";els.productGrid.innerHTML=products.map(p=>{const current=p.sale_price_cents??p.price_cents,badge=p.is_best_seller?"Mais vendido":p.is_featured?"Destaque":p.category;return '<article class="product-card" data-product-id="'+esc(p.id)+'" tabindex="0" role="button" aria-label="Ver '+esc(p.name)+'"><div class="product-media"><span class="product-badge">'+esc(badge)+'</span><span class="heart">♡</span>'+visual(p)+'</div><div class="product-info"><div class="product-meta"><span>'+esc(p.category)+'</span><span>'+esc(p.volume_ml)+' mL</span></div><h3>'+esc(p.name)+'</h3><div class="product-rating">★★★★★ <small>(96)</small></div><div class="product-bottom"><span class="price">'+(p.sale_price_cents?'<del>'+brl(p.price_cents)+'</del>':'')+brl(current)+'</span><button class="quick-buy" type="button" data-quick-add="'+esc(p.id)+'">COMPRAR</button></div></div></article>'}).join("");$$(".product-card",els.productGrid).forEach(card=>{const open=()=>openProduct(card.dataset.productId);card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})});$$("[data-quick-add]",els.productGrid).forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();const p=state.products.find(x=>x.id===btn.dataset.quickAdd);if(p)addToBag(p)}))}
function setFilter(f){state.filter=f;$$(".filter").forEach(b=>b.classList.toggle("is-active",b.dataset.filter===f));renderProducts()}
function reviewsFor(id){return state.reviews.filter(r=>r.product_id===id)}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;state.selectedProduct=p;const reviews=reviewsFor(p.id),price=p.sale_price_cents??p.price_cents,notes=[["Notas de topo",p.top_notes],["Notas de coração",p.heart_notes],["Notas de fundo",p.base_notes]];els.productModalContent.innerHTML='<div class="product-detail"><div class="detail-media">'+visual(p)+'</div><div class="detail-copy"><p class="eyebrow">'+esc(p.brand||"ENZO SALMAZO")+' · '+esc(p.category)+'</p><h2 id="modalTitle">'+esc(p.name)+'</h2><p class="detail-price">'+brl(price)+' · '+esc(p.volume_ml)+' mL</p><p class="detail-desc">'+esc(p.description||p.short_description||"Uma fragrância selecionada para quem procura presença, elegância e identidade.")+'</p><p class="detail-stock">'+(Number(p.stock)>0?esc(p.stock)+" unidade(s) disponíveis":"Disponibilidade a confirmar")+'</p><div class="notes">'+notes.map(([t,v])=>'<div class="note"><strong>'+t+'</strong><span>'+esc((v||[]).join(" · ")||"—")+'</span></div>').join("")+'</div><div class="composition"><strong>Composição</strong><p>'+esc(p.composition||"Informação técnica disponível no atendimento.")+'</p></div><div class="review-block"><h3>Avaliações de clientes</h3>'+(reviews.length?reviews.map(r=>'<div class="review"><div class="review-head"><strong>'+esc(r.customer_name)+'</strong><span class="stars">'+"★".repeat(Number(r.rating))+"☆".repeat(5-Number(r.rating))+'</span></div>'+(r.is_verified_purchase?'<span class="verified">Compra verificada</span>':'')+'<p>'+esc(r.comment)+'</p></div>').join(""):'<p class="detail-desc">Ainda não há avaliações para esta fragrância.</p>')+'</div><div class="detail-actions"><button class="btn btn-gold" type="button" id="addSelectedToBag">Adicionar à sacola</button><button class="btn" type="button" id="buySelectedNow">Comprar agora</button></div></div></div>';els.productOverlay.hidden=false;syncScrollLock();$("#addSelectedToBag")?.addEventListener("click",()=>{addToBag(p);closeProduct()});$("#buySelectedNow")?.addEventListener("click",()=>{addToBag(p);closeProduct();openBag()})}
function closeProduct(){els.productOverlay.hidden=true;state.selectedProduct=null;syncScrollLock()}
function addToBag(p){const e=state.bag.find(i=>i.id===p.id);if(e)e.quantity+=1;else state.bag.push({id:p.id,name:p.name,slug:p.slug,image_url:p.image_url||null,volume_ml:p.volume_ml,unit_price_cents:p.sale_price_cents??p.price_cents,quantity:1});saveBag();renderBag();toast(p.name+" adicionado à sacola")}
function removeFromBag(id){state.bag=state.bag.filter(i=>i.id!==id);saveBag();renderBag()}
function bagTotal(){return state.bag.reduce((s,i)=>s+Number(i.unit_price_cents)*Number(i.quantity),0)}
function renderBag(){const qty=state.bag.reduce((s,i)=>s+Number(i.quantity),0);els.bagCount.textContent=qty;els.bagTotal.textContent=brl(bagTotal());if(!state.bag.length){els.bagItems.innerHTML='<p class="empty-bag">Sua sacola ainda está vazia. Escolha uma fragrância para começar.</p>';els.checkoutBtn.disabled=true;return}els.checkoutBtn.disabled=false;els.bagItems.innerHTML=state.bag.map(i=>'<div class="bag-item">'+(i.image_url?'<img src="'+esc(i.image_url)+'" alt="">':'<div class="bag-art sprite-art '+spriteClass(i)+'"></div>')+'<div><h4>'+esc(i.name)+'</h4><p>'+esc(i.volume_ml)+' mL · qtd. '+esc(i.quantity)+' · '+brl(i.unit_price_cents*i.quantity)+'</p></div><button type="button" data-remove="'+esc(i.id)+'" aria-label="Remover '+esc(i.name)+'">×</button></div>').join("");$$("[data-remove]",els.bagItems).forEach(b=>b.addEventListener("click",()=>removeFromBag(b.dataset.remove)))}
function openBag(){els.bagDrawer.classList.add("is-open");els.bagDrawer.setAttribute("aria-hidden","false");els.drawerMask.hidden=false;syncScrollLock()}
function closeBag(){els.bagDrawer.classList.remove("is-open");els.bagDrawer.setAttribute("aria-hidden","true");els.drawerMask.hidden=true;syncScrollLock()}
function openCheckout(){if(!state.bag.length)return toast("Sua sacola está vazia.");closeBag();els.checkoutSummary.innerHTML=state.bag.map(i=>'<div>'+esc(i.quantity)+'× '+esc(i.name)+' — '+brl(i.unit_price_cents*i.quantity)+'</div>').join("")+'<strong>Total: '+brl(bagTotal())+'</strong>';renderSellerPicker();els.checkoutOverlay.hidden=false;syncScrollLock()}
function closeCheckout(){els.checkoutOverlay.hidden=true;syncScrollLock()}
function syncScrollLock(){document.body.classList.toggle("no-scroll",!els.productOverlay.hidden||!els.checkoutOverlay.hidden||els.bagDrawer.classList.contains("is-open"))}
function setPayment(m){state.payment=m;$$(".payment-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.payment===m));els.paymentDemoBox.innerHTML=m==="pix"?"<strong>PIX</strong><p>O pagamento é confirmado no atendimento após o envio do pedido.</p>":"<strong>Cartão</strong><p>A forma de pagamento por cartão é confirmada no atendimento.</p>"}
els.catalogSearch?.addEventListener("input",e=>{state.search=e.target.value;renderProducts()});
$$(".filter").forEach(b=>b.addEventListener("click",()=>setFilter(b.dataset.filter)));
$$("[data-jump-filter]").forEach(b=>b.addEventListener("click",()=>{setFilter(b.dataset.jumpFilter);$("#catalogo")?.scrollIntoView({behavior:"smooth"})}));
$("[data-close-product]")?.addEventListener("click",closeProduct);els.productOverlay?.addEventListener("click",e=>{if(e.target===els.productOverlay)closeProduct()});
els.bagBtn?.addEventListener("click",openBag);els.closeBag?.addEventListener("click",closeBag);els.drawerMask?.addEventListener("click",closeBag);els.checkoutBtn?.addEventListener("click",openCheckout);
$("[data-close-checkout]")?.addEventListener("click",closeCheckout);els.checkoutOverlay?.addEventListener("click",e=>{if(e.target===els.checkoutOverlay)closeCheckout()});
$$(".payment-tab").forEach(b=>b.addEventListener("click",()=>setPayment(b.dataset.payment)));
els.checkoutForm?.addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.currentTarget),customer=String(d.get("name")||"").trim();if(state.sellers.length&&!state.selectedSellerId)return toast("Selecione o vendedor que te atendeu.");const selected=state.sellers.find(s=>s.seller_id===state.selectedSellerId);toast("Pedido preparado para "+(customer||"cliente")+(selected?" · vendedor: "+selected.display_name:""));state.bag=[];saveBag();renderBag();closeCheckout();e.currentTarget.reset();state.selectedSellerId=null;renderSellerPicker();setPayment("pix")});
document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(!els.checkoutOverlay.hidden)closeCheckout();else if(!els.productOverlay.hidden)closeProduct();else if(els.bagDrawer.classList.contains("is-open"))closeBag()});
loadSiteStatus();loadCatalog();loadSellers();
const headerSearch=document.querySelector("#headerSearch");if(headerSearch){headerSearch.addEventListener("input",e=>{state.search=e.target.value;if(els.catalogSearch)els.catalogSearch.value=e.target.value;renderProducts()});headerSearch.addEventListener("focus",()=>document.querySelector("#catalogo")?.scrollIntoView({behavior:"smooth"}));}
