import{loadCustomerSession,customerSignIn,customerSignUp,customerSignOut,customerPortal}from"./customer-api.js?v=20261001-account1";
const $=s=>document.querySelector(s);
const authView=$("#authView"),accountView=$("#accountView"),authMessage=$("#authMessage"),toast=$("#accountToast");
let boot=null;
const esc=(v="")=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const brl=c=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(c||0)/100);
const statusLabel=s=>({pending:"Pedido recebido",preparing:"Preparando pedido",ready:"Pronto para envio/retirada",shipped:"Enviado",delivered:"Entregue",cancelled:"Cancelado"}[s]||s);
function notify(m){toast.textContent=m;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2600)}
async function bootstrap(){try{boot=(await customerPortal({action:"bootstrap"})).data;render()}catch(e){if(e.message==="LOGIN_REQUIRED"){authView.hidden=false;accountView.hidden=true;return}customerSignOut();authView.hidden=false;accountView.hidden=true;authMessage.textContent="Entre novamente para acessar sua conta."}}
function render(){authView.hidden=true;accountView.hidden=false;const p=boot.profile||{};$("#welcomeName").textContent=p.full_name?"Olá, "+p.full_name.split(" ")[0]:"Minha conta";const pf=$("#profileForm");pf.elements.full_name.value=p.full_name||"";pf.elements.phone.value=p.phone||"";pf.elements.whatsapp_opt_in.checked=p.whatsapp_opt_in!==false;renderAddresses();renderOrders()}
function renderAddresses(){const rows=boot.addresses||[];$("#addressList").innerHTML=rows.length?rows.map(a=>'<article class="address-item"><div class="address-item-top"><div><strong>'+esc(a.label)+(a.is_default?" · principal":"")+'</strong><p>'+esc(a.street)+", "+esc(a.number)+(a.complement?" · "+esc(a.complement):"")+"<br>"+esc(a.neighborhood)+" · "+esc(a.city)+"/"+esc(a.state)+" · CEP "+esc(a.postal_code)+'</p></div></div><div class="address-actions"><button class="account-mini-btn" data-edit-address="'+a.id+'">Editar</button><button class="account-mini-btn danger" data-delete-address="'+a.id+'">Excluir</button></div></article>').join(""):'<p class="account-hint">Nenhum endereço cadastrado.</p>';document.querySelectorAll("[data-edit-address]").forEach(b=>b.onclick=()=>editAddress(b.dataset.editAddress));document.querySelectorAll("[data-delete-address]").forEach(b=>b.onclick=()=>deleteAddress(b.dataset.deleteAddress))}
function renderOrders(){const rows=boot.orders||[];$("#orderList").innerHTML=rows.length?rows.map(o=>'<article class="order-item"><div class="order-head"><div><strong>'+esc(o.public_id)+'</strong><p>'+new Date(o.created_at).toLocaleString("pt-BR")+'</p></div><span class="order-status">'+esc(statusLabel(o.fulfillment_status))+'</span></div><div class="order-lines">'+(o.items||[]).map(i=>esc(i.quantity)+"× "+esc(i.product_name)+" · "+brl(i.line_total_cents)).join("<br>")+'</div><p>Frete: '+brl(o.shipping_price_cents)+' · '+esc(o.shipping_carrier||"—")+" / "+esc(o.shipping_service||"—")+'<br>Total: <strong>'+brl(o.total_cents)+'</strong>'+(o.shipping_delivery_days?'<br>Prazo informado na compra: até '+esc(o.shipping_delivery_days)+' dia(s).':'')+(o.tracking_code?'<br>Rastreio: '+esc(o.tracking_code):'<br>Rastreio automático: em preparação.')+'</p></article>').join(""):'<p class="account-hint">Você ainda não possui pedidos.</p>'}
function editAddress(id){const a=(boot.addresses||[]).find(x=>x.id===id);if(!a)return;const f=$("#addressForm");["id","label","postal_code","street","number","complement","neighborhood","city","state"].forEach(k=>{if(f.elements[k])f.elements[k].value=a[k]||""});f.elements.is_default.checked=!!a.is_default;f.scrollIntoView({behavior:"smooth"})}
async function deleteAddress(id){if(!confirm("Excluir este endereço?"))return;try{await customerPortal({action:"delete_address",id});await bootstrap();notify("Endereço excluído.")}catch(e){notify(e.message)}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();authMessage.textContent="";try{await customerSignIn($("#loginEmail").value,$("#loginPassword").value);await bootstrap()}catch(x){authMessage.textContent=x.message}};
$("#signupForm").onsubmit=async e=>{e.preventDefault();authMessage.textContent="";try{const d=await customerSignUp($("#signupName").value,$("#signupEmail").value,$("#signupPassword").value);if(!d.access_token){authMessage.textContent="Conta criada. Confirme seu e-mail e depois entre.";return}await customerPortal({action:"save_profile",full_name:$("#signupName").value,phone:"",whatsapp_opt_in:true}).catch(()=>{});await bootstrap()}catch(x){authMessage.textContent=x.message}};
$("#logoutBtn").onclick=()=>{customerSignOut();location.reload()};
$("#profileForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await customerPortal({action:"save_profile",full_name:d.get("full_name"),phone:d.get("phone"),whatsapp_opt_in:d.get("whatsapp_opt_in")==="on"});await bootstrap();notify("Dados atualizados.")}catch(x){notify(x.message==="PHONE_INVALID"?"Informe um telefone com DDD.":x.message)}};
$("#addressCep").addEventListener("blur",async e=>{const cep=e.target.value.replace(/\D/g,"");if(cep.length!==8)return;try{const r=await fetch("https://viacep.com.br/ws/"+cep+"/json/");const d=await r.json();if(d.erro)throw new Error();if(String(d.uf).toUpperCase()!=="SP"){notify("No momento, os envios são somente para o Estado de São Paulo.");return}const f=$("#addressForm");f.elements.street.value=d.logradouro||"";f.elements.neighborhood.value=d.bairro||"";f.elements.city.value=d.localidade||"";f.elements.state.value=d.uf||""}catch{notify("CEP não encontrado.")}});
$("#addressForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await customerPortal({action:"save_address",id:d.get("id")||null,label:d.get("label"),postal_code:d.get("postal_code"),street:d.get("street"),number:d.get("number"),complement:d.get("complement"),neighborhood:d.get("neighborhood"),city:d.get("city"),state:d.get("state"),is_default:d.get("is_default")==="on"});f.reset();f.elements.label.value="Principal";f.elements.is_default.checked=true;await bootstrap();notify("Endereço salvo.")}catch(x){notify(x.message==="STATE_NOT_SUPPORTED"?"Envios disponíveis somente para São Paulo.":x.message)}};
if(loadCustomerSession()?.access_token)bootstrap();else{authView.hidden=false;accountView.hidden=true}
