import{SUPABASE_URL,SUPABASE_KEY,loadSession,saveSession,headers,money,esc,table}from"./admin-api.js";
const $=s=>document.querySelector(s),login=$("#loginView"),app=$("#app"),msg=$("#loginMessage"),toast=$("#toast");
function notify(t){toast.textContent=t;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2500)}
async function call(name,payload,auth=true){const r=await fetch(SUPABASE_URL+"/functions/v1/"+name,{method:"POST",headers:auth?headers():{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d?.error||"Falha na operação.");e.status=r.status;throw e}return d}
async function signIn(email,password){const r=await fetch(SUPABASE_URL+"/auth/v1/token?grant_type=password",{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error_description||d?.msg||"Falha no login.");saveSession(d)}
async function createAccess(email,password){if(password.length<8)throw new Error("A senha precisa ter pelo menos 8 caracteres.");const a=await call("seller-bootstrap",{email},false);if(!a.allowed)throw new Error("Este e-mail ainda não foi autorizado no cadastro do vendedor.");const r=await fetch(SUPABASE_URL+"/auth/v1/signup",{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error_description||d?.msg||"Não foi possível criar o acesso.");if(d?.access_token)saveSession(d);return d}
async function refresh(){const d=(await call("seller-portal",{})).data,inv=d.inventory||[],low=d.low_stock||[];$("#sellerName").textContent=d.seller?.name||"Meu estoque";$("#metrics").innerHTML=[["Produtos",inv.length],["Unidades",inv.reduce((s,x)=>s+Number(x.quantity||0),0)],["Alertas",low.length]].map(x=>'<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join("");$("#alerts").innerHTML=low.length?low.map(x=>'<div class="alert-row"><span class="badge-warn">⚠ '+esc(x.product_name)+'</span><span>Restam '+x.quantity+' em '+esc(x.location_name)+'</span></div>').join(""):'<p class="muted">Nenhum alerta de estoque baixo.</p>';$("#inventory").innerHTML=table([["Produto",r=>esc(r.product_name)+" "+esc(r.volume_ml||"")+" mL"],["Local",r=>esc(r.location_name)],["Saldo",r=>r.low_stock?'<span class="badge-warn">⚠ '+r.quantity+'</span>':r.quantity],["Limite",r=>r.low_stock_threshold]],inv);if(d.seller?.can_toggle_site_emergency){$("#emergencyCard").hidden=false;await loadStatus()}login.hidden=true;app.hidden=false}
async function loadStatus(){try{const d=(await call("site-emergency",{action:"get_status"})).data;$("#status").textContent=d.is_online?"Loja online":"Loja fora do ar · "+(d.outage_reason||"")}catch(e){$("#status").textContent="Não foi possível consultar o status."}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();msg.textContent="";try{await signIn($("#email").value.trim(),$("#password").value);await refresh()}catch(x){saveSession(null);msg.textContent=x.message}};
$("#createAccess").onclick=async()=>{msg.textContent="";try{const d=await createAccess($("#email").value.trim(),$("#password").value);if(d.access_token)await refresh();else msg.textContent="Conta criada. Confirme o e-mail recebido e depois entre."}catch(x){msg.textContent=x.message}};
$("#logout").onclick=()=>{saveSession(null);location.reload()};
$("#disable").onclick=async()=>{const reason=$("#reason").value.trim();if(reason.length<3)return notify("Informe a justificativa.");if(!confirm("Confirma desativar a loja temporariamente?"))return;try{await call("site-emergency",{action:"set_status",is_online:false,outage_kind:$("#kind").value,outage_reason:reason});await loadStatus();notify("Loja temporariamente desativada.")}catch(e){notify(e.message)}};
$("#enable").onclick=async()=>{if(!confirm("Confirma colocar a loja online?"))return;try{await call("site-emergency",{action:"set_status",is_online:true,outage_reason:"Reativação pelo vendedor"});await loadStatus();notify("Loja online.")}catch(e){notify(e.message)}};
(async()=>{if(!loadSession()?.access_token)return;try{await refresh()}catch{saveSession(null)}})();